### ISSUE TITLE
Property 'merge' does not exist on type 'typeof jQuery'.ts(2339)

### ISSUE THREAD

**Issue by Faq** [wallabyjs/calculator-sample#2]
in example used [jquery.js](https://github.com/wallabyjs/calculator-sample/blob/master/lib/jquery.js) file getting error like:
![image](https://user-images.githubusercontent.com/322016/113916293-7a009f00-97e8-11eb-8213-6cdb9c711eaa.png)

**Comment by smcenlly** [comment]
This is not a problem. The `Problems` in your screenshot are hints only, being reported by the TypeScript Langauge Service. 

You can see that the merge function does indeed exist in this file on [jquery.js:424](https://github.com/wallabyjs/calculator-sample/blob/master/lib/jquery.js#L424). This problems are likely reported by VS Code thinking it's working with Jquery in our calculator sample and using the type definitions for the latest version of JQuery instead of inferring types for the existing JavaScript file.
